name: Development

on:
  push:
    branches-ignore: [main]
    
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: (cd myCargonaut && npm ci)
      - uses: actions/upload-artifact@v2
        with:
          name: install
          path: myCargonaut
  test:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2

     - uses: actions/download-artifact@v2
       with:
        name: install
     - run: npm test
      
      
        
 
      
