name: Production CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v2
        with:
          node-version: '14'
     - run: (cd myCargonaut && npm ci)
     - run: (cd myCargonaut && npm run build)
     - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: myCargonaut/dist/myCargonaut
#  test:
 #   runs-on: ubuntu-latest
  #  needs: build
   # steps:
