name: Production CI

on:
  push:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Cache node modules
       uses: actions/cache@v2
       env:
        cache-name: cache-node-modules
       with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
     - run: (cd myCargonaut && npm ci)
     
     
    # - uses: actions/upload-artifact@v2
   #    with:
    #      name: Build
     #     path: myCargonaut/dist/myCargonaut
 # test:
   # runs-on: ubuntu-latest
    #needs: build
    #steps:
     # - name: Download Build
      #  uses: actions/download-artifact@v2
       # with:
         # name: Build
         
  test2:
    runs-on: ubuntu:latest
    needs: test
    steps:
     - uses: actions/checkout@v2
     - name: Cache node modules
       uses: actions/cache@v2
       env:
        cache-name: cache-node-modules
       with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
     - run: (cd myCargonaut && npm run test:ci)
        
    
   

