name: Production CI

on:
  push:
    branches: [ main ]
    

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
       matrix:
        node: [ '14', '16' ]
    name: Node ${{ matrix.node }} sample
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v2
       with:
          node-version: ${{ matrix.node }}
     - run: (cd myCargonaut && npm ci)
     
     
    # - uses: actions/upload-artifact@v2
   #    with:
    #      name: Build
     #     path: myCargonaut/dist/myCargonaut
 # test:
   # runs-on: ubuntu-latest
    #needs: build
    #steps:
     # - name: Download Build
      #  uses: actions/download-artifact@v2
       # with:
         # name: Build
         
  test2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14', '16' ]
    name: Node ${{ matrix.node }} sample
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v2
       with:
          node-version: ${{ matrix.node }}
     - run: (cd myCargonaut && npm ci)
        
    
   

